[package]
name = "wgpu-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23"
winit = { version = "0.26", features = ["x11"] }
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2"
